version: '3.5'


services:
  app:
    build:
      context: .
    container_name: Application
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
  #    networks:
  #      - app-network
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-dump/dump:/dump
      - ./scripts/dump.sh:/docker-entrypoint-initdb.d/mongorestore.sh
  #    networks:
  #      - app-network
  Liquibase:
    # Image to be pulled from Docker Hub
    image: liquibase/liquibase:latest
    # Name of the container
    container_name: Liquibase_container
    # Setting depends_on to PostgreSQL container to wait till the service is ready to accept connections
    depends_on:
      db:
        condition: service_healthy
    # Volume to add the liquibase collection of scripts
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./src/main/resources/db/changelog/v1-postgres:/liquibase/changelog/v1-postgres
      - ./src/main/resources/db/changelog/v2-postgres:/liquibase/changelog/v2-postgres
    #      - ./src/main/resources/db/changelog/main-changelog.xml:/liquibase/main-changelog.xml
    # Command to run the liquibase update service
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge
#    name: postgres_net

